# Generated by Django 3.2.9 on 2021-11-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=1000)),
                ('category', models.CharField(choices=[('computer_vision', 'Computer Vision'), ('dashboard', 'Dashboard'), ('other', 'Other')], default='other', max_length=120)),
                ('team_members', models.CharField(max_length=120)),
            ],
        ),
    ]
