# Generated by Django 3.2.9 on 2021-11-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Computer Vision', 'Computer Vision'), ('Dashboard', 'Dashboard'), ('Other', 'Other')], default='Other', max_length=120),
        ),
    ]
